### ISSUE TITLE
Do you plan a Linux version? 

### ISSUE THREAD

**Issue by MuddyVT** [aaknitt/voxcall#1]
Andy, I tried this on an AMD PC and had arm errors as expected. 
Just curious if you plan to release for non-arm Linux ?
Eventually I would like to run this on my proxmox server with a small distro.

**Comment by aaknitt** [comment]
Yes, I'll likely do this...working through a few bug fixes and tweaks for a future release before supporting more platforms.

**Comment by aaknitt** [comment]
Try [this](http://radioetcetera.site/radioetcetera/files/voxcall_Ubuntu.tgz) and let me know if it works for you.  Built on Ubuntu.

**Comment by MuddyVT** [comment]
Thank you Andy,
I will try it and let you know!
Much appreciated

**Comment by MuddyVT** [comment]
Andy,
It came up with a libpython3.6 error.  Probably as I am running Python 2.x
on that old box.
I will try on something newer tonight.
David

**Comment by aaknitt** [comment]
Can you copy the full error you received?  There shouldn't be a Python dependency once it's been compiled into a binary executable.

**Comment by MuddyVT** [comment]
Ok will do.
At the moment I finally have buster and TTD68(don’t ask) and voxcall all
working on a new Pi4.   While they test a bit I will jump over to that
Linux test.
Thank you

**Comment by MuddyVT** [comment]
Struggling to copy paste. Can you read the error at the bottom on this
photo?

**Comment by aaknitt** [comment]
I'm not seeing a photo

**Comment by cfc62** [comment]
Running Ubuntu, tried the executable and got this result. Note, I didn't edit the .cfg file at all. 

~/voxcall$ ./voxcall
Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 13, in <module>
  File "/home/andy/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "pkg_resources/__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[1551094] Failed to execute script pyi_rth_pkgres

**Comment by mjmikolay** [comment]
Has anyone been able to get the Ubuntu version working? I'm getting the same error as @cfc62 above. Would love to use this on a linux headless system to pull in some additional scanners. Thanks in advance?

**Comment by aaknitt** [comment]
The build linked above was on Ubuntu 18.  When I get some time I can try a build on 20, but you can also run the Python file directly from source, you'll just have to work through installing dependencies.  
```
python3 voxcall.py
```
You'll likely get errors due to missing packages...install them one at a time until the errors are gone and it runs.

**Comment by blackwellj** [comment]
Would really appreciate a ubuntu build

**Comment by Hubdude24** [comment]
This still getting work on?
